"use client";
import { FormEvent, useEffect, useState } from "react";
type Item = { id: number; invoiceDate: string; invoiceNumber: string; amount: string; status: string };
export function ReconciliationForm() {
  const [items, setItems] = useState<Item[]>([]); const [invoiceDate, setInvoiceDate] = useState(""); const [invoiceNumber, setInvoiceNumber] = useState(""); const [amount, setAmount] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/reconciliation").then(r => r.ok ? r.json() : { items: [] }).then(d => setItems(d.items ?? [])).catch(() => setItems([])); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await fetch("/api/reconciliation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ invoiceDate, invoiceNumber, amount }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setItems(current => [data.item, ...current]); setInvoiceDate(""); setInvoiceNumber(""); setAmount(""); setMessage("已提交，等待往来明细复核。"); } catch (error) { setMessage(error instanceof Error ? error.message : "提交失败，请重试"); } finally { setSaving(false); } }
  return <><form className="entry-form" onSubmit={submit}><label>时间<input type="date" value={invoiceDate} onChange={e => setInvoiceDate(e.target.value)} required /></label><label>发票号<input placeholder="例如 2632200000…" value={invoiceNumber} onChange={e => setInvoiceNumber(e.target.value)} required /></label><label>金额（元）<input type="number" step="0.01" placeholder="0.00" value={amount} onChange={e => setAmount(e.target.value)} required /></label><button type="submit" disabled={saving}>{saving ? "提交中…" : "提交复核"}</button></form>{message && <p className="message" role="status">{message}</p>}<section className="records"><div className="section-heading"><div><p className="eyebrow">已提交</p><h2>本次待复核明细</h2></div><span>{items.length} 笔</span></div>{items.length === 0 ? <p className="empty">还没有提交记录。请先填写上方三项。</p> : <div className="table-wrap"><table><thead><tr><th>时间</th><th>发票号</th><th>金额</th><th>状态</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.invoiceDate}</td><td>{item.invoiceNumber}</td><td>¥ {Number(item.amount).toLocaleString("zh-CN", { minimumFractionDigits: 2 })}</td><td><span className="status">{item.status}</span></td></tr>)}</tbody></table></div>}</section></>;
}
